x-logging: &default-logging
  driver: fluentd
  options:
    fluentd-address: "localhost:24224"
    fluentd-async: "true"
    tag: "docker.{{.Name}}"

services:
  victoria-logs:
    image: victoriametrics/victoria-logs:v1.49.0@sha256:d0c8441ca886e055c519daa89fb0a399bfdc0908fe85700d603beb2126d714c6
    command:
      - -storageDataPath=/vlogs
      - -loggerFormat=json
      - -retentionPeriod=7d
    ports:
      - "9428:9428"
    volumes:
      - victoria-logs-data:/vlogs

  fluentbit:
    image: cr.fluentbit.io/fluent/fluent-bit:5.0.4@sha256:7b4cc81b02155855337f7184e128fc078fd9d6240d99236285233de931b9a929
    command:
      - --config=/fluent-bit/etc/fluent-bit.yaml
    ports:
      - "24224:24224"
    volumes:
      - ./config/fluentbit:/fluent-bit/etc
    depends_on:
      - victoria-logs

  victoria-traces:
    image: victoriametrics/victoria-traces:v0.8.0@sha256:b00d788b51a8f6c16b5e4cb5d94649e6b8a4c76ba9db8ac11d8b151198b06129
    command:
      - -storageDataPath=/vtraces
      - -loggerFormat=json
    ports:
      - "10428:10428"
    depends_on:
      - fluentbit
    volumes:
      - victoria-traces-data:/vtraces
    logging: *default-logging

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.140.1@sha256:5901567d6f684547bafee53f02403869b5655e13a4e0af65aa6ae9f6301075d9
    command:
      - --config=/conf/collector.yaml
    ports:
      - "4317:4317"
      - "8888:8888"
    volumes:
      - ./config/otel:/conf
    depends_on:
      - victoria-traces
    logging: *default-logging

  app-a:
    # build: ./fastapi_app/
    image: ghcr.io/oscaromeu/fastapi-observability/app:0.1.0@sha256:f087c724a0232efae75cda2fb3f1dfb5b2b4b61f0f8d667336855b123af11938
    ports:
      - "8000:8000"
    depends_on:
      - fluentbit
      - otel-collector
    environment:
      APP_NAME: "app-a"
      OTLP_GRPC_ENDPOINT: "http://otel-collector:4317"
    logging: *default-logging

  app-b:
    # build: ./fastapi_app/
    image: ghcr.io/oscaromeu/fastapi-observability/app:0.1.0@sha256:f087c724a0232efae75cda2fb3f1dfb5b2b4b61f0f8d667336855b123af11938
    ports:
      - "8001:8000"
    depends_on:
      - fluentbit
      - otel-collector
    environment:
      APP_NAME: "app-b"
      OTLP_GRPC_ENDPOINT: "http://otel-collector:4317"
    logging: *default-logging

  app-c:
    # build: ./fastapi_app/
    image: ghcr.io/oscaromeu/fastapi-observability/app:0.1.0@sha256:f087c724a0232efae75cda2fb3f1dfb5b2b4b61f0f8d667336855b123af11938
    ports:
      - "8002:8000"
    depends_on:
      - fluentbit
      - otel-collector
    environment:
      APP_NAME: "app-c"
      OTLP_GRPC_ENDPOINT: "http://otel-collector:4317"
    logging: *default-logging

  prometheus:
    image: prom/prometheus:v2.51.2@sha256:4f6c47e39a9064028766e8c95890ed15690c30f00c4ba14e7ce6ae1ded0295b1
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus:/workspace
    command:
      - --config.file=/workspace/prometheus.yml
      - --enable-feature=exemplar-storage
    depends_on:
      - fluentbit
    logging: *default-logging

  grafana:
    image: grafana/grafana:12.4.0@sha256:b0ae311af06228bcfd4a620504b653db80f5b91e94dc3dc2a5b7dab202bcde20
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: victoriametrics-logs-datasource
    volumes:
      - ./config/grafana/:/etc/grafana/provisioning/datasources
      - ./config/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./config/dashboards:/etc/grafana/dashboards
    depends_on:
      - fluentbit
      - prometheus
    logging: *default-logging

volumes:
  victoria-logs-data:
  victoria-traces-data:
